version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger-opentelemetria
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    networks:
      - pos-elite-network

networks:
  pos-elite-network:
    driver: bridge
