version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger-opentelemetria
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    networks:
      - pos-elite-network
  
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - pos-elite-network

networks:
  pos-elite-network:
    driver: bridge
