@API_URL = http://localhost:8080/kafka

############################################################################
### GET
GET {{API_URL}}/hello HTTP/1.1

############################################################################
### GET
GET {{API_URL}}/hello-key HTTP/1.1

############################################################################
### GET
GET {{API_URL}}/object HTTP/1.1